CREATE TABLE `tasks` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`listId` INT NOT NULL,
	`title` VARCHAR(255),
	`updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (`id`)
);