CREATE TABLE `taskLists` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`taskId` INT NOT NULL,
	`listId` INT NOT NULL,
	`updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (`id`)
);